name: linux

on: 
  push:
  pull_request:

jobs:

  build-linux:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: |
        sudo apt update
        cd ../..
        git clone https://github.com/open-ephys/plugin-GUI.git --branch testing-juce8
        sudo ./plugin-GUI/Resources/Scripts/install_linux_dependencies.sh
        cd plugin-GUI/Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: |
        cd Build
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
        make
#    - name: test
#      run: cd build && ctest
    - name: deploy
      if: github.ref == 'refs/heads/main'
      env:
        ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
        build_dir: "Build"
        package: RHDRecordingController-linux
      run: |
        plugin_api=$(grep -rnw ../../plugin-GUI/Source -e '#define PLUGIN_API_VER' | grep -Eo "[0-9]*" | tail -1)
        tag=$(grep -w Source/OpenEphysLib.cpp -e 'info->libVersion' | grep -Eo "[0-9]+.[0-9]+.[0-9]+")
        new_plugin_ver=$tag-API$plugin_api
        mkdir plugins 
        cp -r $build_dir/*.so plugins
        mkdir shared
        cp Resources/libokFrontPanel.so shared
        cp Resources/intan_rec_controller_7310.bit shared
        zipfile=${package}_${new_plugin_ver}.zip
        zip -r -X $zipfile plugins shared
        curl -H "X-JFrog-Art-Api:$ARTIFACTORY_ACCESS_TOKEN" -T $zipfile "https://openephys.jfrog.io/artifactory/RHDRecordingController-plugin/linux/$zipfile"
